// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_Q2_kt_nSTOCPDemDVCXVimaU1vLiar8',
    appId: '1:87234020223:web:fcad8d80915fb34f7c104a',
    messagingSenderId: '87234020223',
    projectId: 'saifproject-701cc',
    authDomain: 'saifproject-701cc.firebaseapp.com',
    databaseURL: 'https://saifproject-701cc-default-rtdb.firebaseio.com',
    storageBucket: 'saifproject-701cc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCcFhbX3m9xaUbaCvsyXaPCeic1_PD50A',
    appId: '1:87234020223:android:155ff21bb354575e7c104a',
    messagingSenderId: '87234020223',
    projectId: 'saifproject-701cc',
    databaseURL: 'https://saifproject-701cc-default-rtdb.firebaseio.com',
    storageBucket: 'saifproject-701cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZtEn0KHqMPO35Jjl6Yjk9U18zDV-aNkk',
    appId: '1:87234020223:ios:bbcf725159ed39327c104a',
    messagingSenderId: '87234020223',
    projectId: 'saifproject-701cc',
    databaseURL: 'https://saifproject-701cc-default-rtdb.firebaseio.com',
    storageBucket: 'saifproject-701cc.appspot.com',
    iosClientId: '87234020223-vvlpa57vct51n4lefuiufj248u7jcl5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.newproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZtEn0KHqMPO35Jjl6Yjk9U18zDV-aNkk',
    appId: '1:87234020223:ios:bbcf725159ed39327c104a',
    messagingSenderId: '87234020223',
    projectId: 'saifproject-701cc',
    databaseURL: 'https://saifproject-701cc-default-rtdb.firebaseio.com',
    storageBucket: 'saifproject-701cc.appspot.com',
    iosClientId: '87234020223-vvlpa57vct51n4lefuiufj248u7jcl5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.newproject',
  );
}
